language: php

php:
  - 7.0

matrix:
  include:
    - php: 7.1

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction --dev

before_script:
  - cp .env.travis .env

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_script: ./codeclimate.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
