language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - setup=basic
    - coverage=false

matrix:
  include:
    - php: 5.6
      env: setup=stable
    - php: 7.1
      env: coverage=true

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi

before_script:
  - cp .env.travis .env

script:
  - if [[ $coverage = 'false' ]]; then vendor/bin/phpunit; fi
  - if [[ $coverage = 'true' ]]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml; fi

after_script: ./codeclimate.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
